name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      screeps_version:
        description: Screeps package version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        build-args: |
          SCREEPS_VERSION=${{ github.event.inputs.screeps_version }}
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          eadword/screeps-server:latest
          eadword/screeps-server:${{ github.event.inputs.screeps_version }}
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
